service: certification

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  timeout: 180
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: 
        - s3:ListBucket
        - s3:PutObject
      Resource: "arn:aws:s3:::training-certificates.neo4j.com/*"

custom:
  pythonRequirements:
    zip: true

plugins:
  - serverless-python-requirements

functions:
  generate-certificate:
      name: GenerateCertificate
      handler: handler.generate_certificate
      events:
        - schedule: rate(1 hour)

package:
  exclude:
    - a/**
