version: 2
jobs:
  build:
    working_directory: ~/circleci-gh-pages
    docker:
      - image: circleci/node:6.12.0
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y awscli python3
      - run: npm install serverless
#      - run: aws --region eu-west-1 s3 sync ~/circleci-gh-pages/email-templates/ s3://training-certificate-emails.neo4j.com --delete
      - run: echo $ENV_YAML | base64 --decode --ignore-garbage > ~/circleci-gh-pages/env.yml
      - run: ./node_modules/serverless/bin/serverless deploy

workflows:
  version: 2
  developer-pages:
    jobs:
      - build:
          filters:
            branches:
              only: master
